### ISSUE TITLE
大佬你好，docker 启动frontend一直不成功

### ISSUE THREAD

**Issue by ahwdy98** [daodao97/chatdoc#16]
chatdoc-frontend | > client@0.0.0 dev /data
chatdoc-frontend | > vite --host
chatdoc-frontend | 
chatdoc-frontend | 
chatdoc-frontend |   VITE v4.2.1  ready in 906 ms
chatdoc-frontend | 
chatdoc-frontend |   ➜  Local:   http://localhost:5173/
chatdoc-frontend |   ➜  Network: http://172.29.0.3:5173/
chatdoc-frontend | node:internal/errors:490
chatdoc-frontend |     ErrorCaptureStackTrace(err);
chatdoc-frontend |     ^
chatdoc-frontend | 
chatdoc-frontend | Error: ENOSPC: System limit for number of file watchers reached, watch '/data/.pnpm-store/v3/files/91/4a1eaca75f67e09109a8ba403cf5d07fe3107d55cfeca64592d63c5ced82e81403d699297cfc45272d4026cf094ebee301db105d868a1c952fdf0aea81d4f0'
chatdoc-frontend |     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
chatdoc-frontend |     at Object.watch (node:fs:2350:36)
chatdoc-frontend |     at createFsWatchInstance (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50328:17)
chatdoc-frontend |     at setFsWatchListener (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50375:15)
chatdoc-frontend |     at NodeFsHandler._watchWithNodeFs (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50530:14)
chatdoc-frontend |     at NodeFsHandler._handleFile (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50594:23)
chatdoc-frontend |     at NodeFsHandler._addToNodeFs (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50836:21)
chatdoc-frontend | Emitted 'error' event on FSWatcher instance at:
chatdoc-frontend |     at FSWatcher._handleError (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:52028:10)
chatdoc-frontend |     at NodeFsHandler._addToNodeFs (file:///data/node_modules/.pnpm/vite@4.2.1_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-79892de8.js:50844:18) {
chatdoc-frontend |   errno: -28,
chatdoc-frontend |   syscall: 'watch',
chatdoc-frontend |   code: 'ENOSPC',
chatdoc-frontend |   path: '/data/.pnpm-store/v3/files/91/4a1eaca75f67e09109a8ba403cf5d07fe3107d55cfeca64592d63c5ced82e81403d699297cfc45272d4026cf094ebee301db105d868a1c952fdf0aea81d4f0',
chatdoc-frontend |   filename: '/data/.pnpm-store/v3/files/91/4a1eaca75f67e09109a8ba403cf5d07fe3107d55cfeca64592d63c5ced82e81403d699297cfc45272d4026cf094ebee301db105d868a1c952fdf0aea81d4f0'
chatdoc-frontend | }
chatdoc-frontend | 

找不到原因。

**Comment by daodao97** [comment]
我看好些人docker启动报错，我周末看看咋优化一下
