### ISSUE TITLE
启动后端时提示ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by jdukwjdo** [daodao97/chatdoc#25]
启动后端时，提示导入包错误了，完整信息：
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.123->-r requirements.txt (line 5)) (1.0.0)
Traceback (most recent call last):
  File "/app/chatdoc/server/main.py", line 3, in <module>
    from doc_util import Doc
  File "/app/chatdoc/server/doc_util.py", line 9, in <module>
    from epub2txt import epub2txt
  File "/usr/local/lib/python3.10/dist-packages/epub2txt/__init__.py", line 2, in <module>
    from .epub2txt import epub2txt
  File "/usr/local/lib/python3.10/dist-packages/epub2txt/epub2txt.py", line 10, in <module>
    from collections import Iterable  # < py38
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by aaaawt** [comment]
python 3.9中Iterable来自collections包，3.10中在collections.abc包。所以改包名或者改python版本即可
