### ISSUE TITLE
一直索引构建中。。。

### ISSUE THREAD

**Issue by lonelysheeep** [daodao97/chatdoc#34]
请问可以不用docker,直接运行前后端可以吗，我直接运行前后端上传文件后一直在索引构建中是什么原因呢

**Comment by melody4482** [comment]
You can run the frontend and backend at once using other hosting app.
Specially, AWS EC2 instance is really good stuff. That is one of a system and you can run it, and using nginx and certbot, you can join it to the domain.
Hope you success

**Comment by daodao97** [comment]
> 请问可以不用docker,直接运行前后端可以吗，我直接运行前后端上传文件后一直在索引构建中是什么原因呢
> 
> 
文件越大，索引构建时间越长，可以多刷新一下页面看看状态，也可以看下后端日志

**Comment by lonelysheeep** [comment]
还有两个问题，第一个是有些pdf文件点击上传没有反应这是啥原因呢？
第二个问题是构建过程中报错怎么解决？
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py22\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Anaconda3\envs\py22\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Anaconda3\envs\py22\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Anaconda3\envs\py22\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\responses.py", line 174, in __call__
    await self.background()
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\background.py", line 43, in __call__
    await task()
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "D:\Anaconda3\envs\py22\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\Anaconda3\envs\py22\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Anaconda3\envs\py22\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Anaconda3\envs\py22\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\中信建投证券\chatdoc-master\server\main.py", line 97, in file_task
    doc.build_txt(res['doc_type'])
  File "D:\中信建投证券\chatdoc-master\server\doc_util.py", line 69, in build_txt
    self.extract_pdf()
  File "D:\中信建投证券\chatdoc-master\server\doc_util.py", line 88, in extract_pdf
    file.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufb01' in position 885: illegal multibyte sequence
