### ISSUE TITLE
docker-compose up 提示找不到docx2txt

### ISSUE THREAD

**Issue by Wjun0** [daodao97/chatdoc#7]
chatdoc-backend | Traceback (most recent call last):
chatdoc-backend |   File "/data/main.py", line 3, in <module>
chatdoc-backend |     from doc_util import Doc
chatdoc-backend |   File "/data/doc_util.py", line 12, in <module>
chatdoc-backend |     import docx2txt
chatdoc-backend | ModuleNotFoundError: No module named 'docx2txt'
chatdoc-backend exited with code 1

**Comment by Wjun0** [comment]
已经有人提出来了
